version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./tmp/elastic:/usr/share/elasticsearch/data
    ports:
      - "localhost:9200:9200"
